from pathlib import Path

path = Path("psa_sniper/identity.py")
text = path.read_text(encoding="utf-8")
old = '''    subjects = _subject_terms(subject_value or "", exclude=card_parts)\n    if not subjects:\n        subjects = _subject_terms(listing.title, exclude=card_parts)\n        # Prefer meaningful words immediately before the card number. This avoids\n        # treating set/franchise words as the subject in titles such as\n        # "Team Rocket's Mewtwo ... 237/193 M2A ... PSA 10".\n        title_n = normalize_text(listing.title)\n        card_n = normalize_text(card_number)\n        position = title_n.find(card_n) if card_n else -1\n        if position > 0:\n            before_number = _subject_terms(title_n[:position], exclude=card_parts)\n            if before_number:\n                subjects = before_number[-2:]\n    if not subjects:\n        return None\n'''
new = '''    subjects = _subject_terms(subject_value or "", exclude=card_parts)\n    if not subjects:\n        subjects = _subject_terms(listing.title, exclude=card_parts)\n        # Prefer nearby card-name terms only after removing obvious set/publication\n        # words. This keeps "Monkey D Luffy ... WSJ ... 043" as Monkey/Luffy,\n        # while "Team Rocket's Mewtwo ... 237/193" resolves to Mewtwo.\n        title_n = normalize_text(listing.title)\n        card_n = normalize_text(card_number)\n        position = title_n.find(card_n) if card_n else -1\n        if position > 0:\n            before_number = _subject_terms(title_n[:position], exclude=card_parts)\n            noise = {"team", "rocket", "dream", "weekly", "shonen", "jump", "wsj"}\n            nearby = [term for term in before_number if term not in noise]\n            if nearby:\n                subjects = nearby[-2:]\n    if not subjects:\n        return None\n'''
if old not in text:
    raise RuntimeError("patched subject block not found")
path.write_text(text.replace(old, new, 1), encoding="utf-8")
print("subject selection refined")
