from __future__ import annotations

from datetime import timedelta
from typing import Any

from .state import default_state
from .util import iso_z, utc_now


def demo_state() -> dict[str, Any]:
    now = utc_now()
    state = default_state()
    state["history"] = [
        {
            "item_id": "demo-1",
            "title": "2021 Japanese Promo Pikachu PSA 10",
            "url": "https://www.ebay.de/",
            "image_url": None,
            "image_urls": [],
            "price": {"value": 129.0, "currency": "EUR"},
            "shipping": {"value": 5.49, "currency": "EUR"},
            "total_cost": {"value": 134.49, "currency": "EUR"},
            "created_at": iso_z(now - timedelta(minutes=8)),
            "end_at": None,
            "first_seen_at": iso_z(now - timedelta(minutes=7)),
            "last_seen_at": iso_z(now - timedelta(minutes=7)),
            "seller": "demo_seller",
            "seller_feedback_percentage": 99.8,
            "seller_feedback_score": 342,
            "buying_options": ["FIXED_PRICE"],
            "pure_auction": False,
            "condition": "Graded",
            "returns_accepted": True,
            "item_location_country": "DE",
            "matched_queries": ["PSA 10 Pokemon", "PSA10 Pokemon"],
            "score": 19,
            "is_hit": True,
            "reasons": [
                "PSA-Cert bestätigt GEM MT 10",
                "niedrige PSA-10-Population: 9",
                "Variante/Parallel fehlt im Titel",
                "Kartennummer fehlt im Titel",
                "Gesamtkosten ca. 39% unter Vergleichswert",
            ],
            "warnings": [],
            "cert_number": "12345678",
            "cert_source": "OCR (beschriftet)",
            "cert_confidence": 0.86,
            "cert_trusted": True,
            "cert": {
                "cert_number": "12345678",
                "valid": True,
                "grade": "GEM MT 10",
                "year": "2021",
                "brand_title": "POKEMON JPN. S-P PROMO",
                "subject": "PIKACHU",
                "card_number": "227",
                "category": "TCG Cards",
                "variety": "PROMO",
                "population": 9,
                "population_higher": 0,
                "estimate": {"value": 220, "currency": "EUR"},
                "recent_sales": [],
                "source_url": "https://www.psacard.com/",
                "data_source": "Demo",
            },
            "market_value": {
                "money": {"value": 220, "currency": "EUR"},
                "source": "PSA ähnliche Verkäufe",
                "confidence": "hoch",
                "sample_size": 4,
            },
            "discount_pct": 0.3887,
        },
        {
            "item_id": "demo-2",
            "title": "Topps Chrome Bundesliga PSA10 #16",
            "url": "https://www.ebay.de/",
            "image_url": None,
            "image_urls": [],
            "price": {"value": 46.0, "currency": "EUR"},
            "shipping": {"value": 0.0, "currency": "EUR"},
            "total_cost": {"value": 46.0, "currency": "EUR"},
            "created_at": iso_z(now - timedelta(minutes=31)),
            "end_at": None,
            "first_seen_at": iso_z(now - timedelta(minutes=30)),
            "last_seen_at": iso_z(now - timedelta(minutes=30)),
            "seller": "cards_de",
            "seller_feedback_percentage": 98.7,
            "seller_feedback_score": 88,
            "buying_options": ["FIXED_PRICE", "BEST_OFFER"],
            "pure_auction": False,
            "condition": "Graded",
            "returns_accepted": False,
            "item_location_country": "DE",
            "matched_queries": ["PSA10 Topps Chrome"],
            "score": 13,
            "is_hit": True,
            "reasons": ["PSA-Cert bestätigt GEM MT 10", "sehr niedrige PSA-10-Population: 2", "Variante/Parallel fehlt im Titel"],
            "warnings": [],
            "cert_number": "87654321",
            "cert_source": "Item-Specifics",
            "cert_confidence": 1.0,
            "cert_trusted": True,
            "cert": {
                "cert_number": "87654321", "valid": True, "grade": "10", "year": "2020",
                "brand_title": "TOPPS CHROME BUNDESLIGA", "subject": "TAIWO AWONIYI",
                "card_number": "16", "category": "Soccer", "variety": "X-FRACTOR",
                "population": 2, "population_higher": 0, "estimate": {"value": 80, "currency": "EUR"},
                "recent_sales": [], "source_url": "https://www.psacard.com/", "data_source": "Demo"
            },
            "pricing_identity": {
                "version": 2, "card_number": "16", "subjects": ["taiwo", "awoniyi"],
                "terms": ["taiwo", "awoniyi"], "year": "2020", "set_code": None,
                "language": None, "edition": None, "variant": "REFRACTOR",
            },
            "point130_query": "taiwo awoniyi 16 PSA 10",
            "market_value": {
                "money": {"value": 80, "currency": "EUR"},
                "source": "130point verkaufte PSA-10-Comps", "confidence": "mittel",
                "sample_size": 2, "market_type": "point130_sold", "required_edge": 0.15,
                "price_low": 76, "price_high": 84, "dispersion": 0.10,
            },
            "discount_pct": 0.425,
        },
        {
            "item_id": "demo-3",
            "title": "One Piece Nami PSA 10 Card",
            "url": "https://www.ebay.de/",
            "image_url": None,
            "image_urls": [],
            "price": {"value": 84.0, "currency": "EUR"},
            "shipping": {"value": 6.0, "currency": "EUR"},
            "total_cost": {"value": 90.0, "currency": "EUR"},
            "created_at": iso_z(now - timedelta(hours=1)),
            "end_at": iso_z(now + timedelta(days=2)),
            "first_seen_at": iso_z(now - timedelta(minutes=58)),
            "last_seen_at": iso_z(now - timedelta(minutes=58)),
            "seller": "op_cards",
            "seller_feedback_percentage": 99.2,
            "seller_feedback_score": 1240,
            "buying_options": ["AUCTION"],
            "pure_auction": True,
            "condition": "Graded",
            "returns_accepted": None,
            "item_location_country": "DE",
            "matched_queries": ["PSA 10 One Piece Card Game"],
            "score": 8,
            "is_hit": False,
            "reasons": ["PSA-Cert bestätigt GEM MT 10", "PSA-10-Population: 21"],
            "warnings": ["reine Auktion: aktueller Preis ist kein Sofortkauf-Fehlpreis"],
            "cert_number": "11223344",
            "cert_source": "Titel",
            "cert_confidence": 0.97,
            "cert_trusted": True,
            "cert": {
                "cert_number": "11223344", "valid": True, "grade": "10", "year": "2023",
                "brand_title": "ONE PIECE CARD GAME", "subject": "NAMI", "card_number": "SP",
                "category": "TCG Cards", "variety": "SPECIAL PARALLEL", "population": 21,
                "population_higher": 0, "estimate": None, "recent_sales": [],
                "source_url": "https://www.psacard.com/", "data_source": "Demo"
            },
            "market_value": None,
            "discount_pct": None,
        },
    ]
    state["runs"] = [
        {
            "started_at": iso_z(now - timedelta(minutes=10)),
            "completed_at": iso_z(now - timedelta(minutes=7)),
            "queries_used": 12,
            "listings_seen": 302,
            "fresh_listings": 37,
            "detailed_candidates": 18,
            "psa_lookups": 7,
            "hits": 2,
            "near_hits": 1,
            "ebay_calls": 30,
            "notes": [],
        }
    ]
    return state
